
# Setup
title:            Reminiz Tips
tagline:          'Improve everyday.'
description:      'This is so cool bro !'
url:            http://antoine-cha.github.io/tips/
baseurl:             ''
paginate:            5
permalink: pretty

  # About/contact
author:
  name: Mark Otto
email: markdotto@gmail.com

  # Custom vars
version: 1.0.0

gems:
  - jekyll-paginate

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed
  sass_dir: _scss
